commandchar: .
buffer: 100
log:
    dir: logs
    filename_template: borgil--{{date}}.log
    date_format: YYYY-MM-DD--HH-mm-ss
    console: true
    debug: false
dbdir: db
admins:
    - saltire
transports:
    oftc:
        type: irc
        host: irc.oftc.net
        nick: borgil
        opts:
            port: 6697
            secure: true
            selfSigned: true
            userName: borgil
            realName: Borgil of Menelvagor
    i2p:
        type: irc
        host: localhost
        nick: borgil
        opts:
            port: 6668
            userName: borgil
            realName: Borgil of Menelvagor
    telegram:
        type: telegram
        token: your-telegram-token
        chat_ids:
            - 123456789
plugins:
    broadcast:
        broadcast_all: false
        template: '[{{{source}}}] <{{{from_name}}}> {{{text}}}'
        target_sets:
            -
                -
                    transport: oftc
                    channel: '#torontocrypto'
                -
                    transport: i2p
                    channel: '#torontocrypto'
    ddg-scraper:
        template: '[DDG] {{{title}}} | {{url}}'
    modes:
        i2p:
            - '+B'
    nickserv:
        networks:
            oftc:
                password: password
                success: 'You are successfully identified'
                channels:
                    - '#torontocrypto'
                channel_keywords:
                    '#torontocrypto': keyword
            i2p:
                nick_first: true
                password: password
                success: 'You are now identified'
                channels:
                    - '#torontocrypto'
    rss:
        autostart: false
        interval: 10
        item_template: '[{{color}}{{name}}{{reset}}] {{{title}}} | {{url}}'
        list_template: ' {{network}} {{target}} {{color}}{{name}}{{reset}} {{url}}'
    url:
        template: '[ {{{title}}} ] - {{domain}}'
    youtube:
        api_key: yourGoogleApiKey
        url_template: '[YouTube] {{{title}}} | Length: {{length}} | Channel: {{channel}} | Uploaded: {{date}} | Views: {{views}} | +{{likes}} -{{dislikes}} | Comments: {{comments}}'
        search_template: '[YouTube] {{{title}}} | {{url}} | Length: {{length}} | Channel: {{channel}} | Uploaded: {{date}} | Views: {{views}} | +{{likes}} -{{dislikes}} | Comments: {{comments}}'
